[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = { version = "0.10.71", features=["vendored"] }
reqwest = { version = "0.12.15", features=["blocking"] }
rocket = "0.5.1"
